### ISSUE TITLE
Update to naga 0.13

### ISSUE THREAD

**Issue by Elabajaba** [bevyengine/naga_oil#33]
I had a quick look at this, and it seemed confusing (especially since naga doesn't have a changelog yet, and https://github.com/gfx-rs/naga/pull/2266 seems to have changed a bunch of stuff).

**Comment by mockersf** [comment]
doing this patch far from the next Bevy release would mean it would be harder to publish a patch that would be picked up by the current version of Bevy. That said, I don't know if there are already breaking changes merged.

**Comment by Elabajaba** [comment]
> Doing this update far from the next Bevy release would mean it would be harder to publish a patch that would be picked up by the current version of Bevy. 

Agreed

> 
> And not doing it means it will be harder to update Bevy to the latest version of wgpu...

It's not possible to update bevy to wgpu 0.17 without first updating naga_oil

**Comment by robtfm** [comment]
i assume there is no intention to bump wgpu for 0.11.1? 

if there is i'll prioritise this, otherwise i'll look later (if nobody beats me to it).

there are already breaking changes in naga_oil from #32, which i hope will be used in the bevy point release as well.

**Comment by Elabajaba** [comment]
> i assume there is no intention to bump wgpu for 0.11.1?

I don't think there's any need for a major wgpu bump, and I don't think we've ever bumped it for a patch release?

**Comment by VitalyAnkh** [comment]
The development version of bevy should use a development version of naga_oil, or naga_oil lives in the same repository with bevy's crates. The latter won't stop people from using naga_oil as a standalone tool.

**Comment by JMS55** [comment]
I would appreciate a version of naga_oil compatible with naga 0.13, and keeping up with upstream naga regardless of bevy version in the future.

When developing bevy, I often need to test a git version of wgpu/naga, which is impossible without first updating naga_oil :(.
