### ISSUE TITLE
naga_oil does not support preprocessor definitions that end in numbers

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/naga_oil#62]
Reported in https://github.com/bevyengine/bevy/pull/10237

@IceSentry believes this is a naga_oil problem, not a naga limitation.

**Comment by robtfm** [comment]
preprocessor definitions that end in numbers or _ should be fine i think. the problem is that struct members can't end in numbers of underscores - the `.uv_1` in this case.

it's captured (though badly named) in #30

**Comment by alice-i-cecile** [comment]
Great, closing as a duplicate :)
