### ISSUE TITLE
Confusing shader_defs field in ComposableModuleDescriptor and NagaModuleDescriptor

### ISSUE THREAD

**Issue by floppyhammer** [bevyengine/naga_oil#72]
What's the difference between `shader_defs` in `ComposableModuleDescriptor` and that in `NagaModuleDescriptor`? I can understand why pass defs when calling `make_naga_module`, but what do we do with the defs when calling `add_composable_module`? Should I keep them the same during these two calls? As I tested, only the defs past to `make_naga_module` took effect.

```rs
#[derive(Default)]
pub struct ComposableModuleDescriptor<'a> {
    pub source: &'a str,
    pub file_path: &'a str,
    pub language: ShaderLanguage,
    pub as_name: Option<String>,
    pub additional_imports: &'a [ImportDefinition],
    pub shader_defs: HashMap<String, ShaderDefValue>,
}
```

```rs
#[derive(Default)]
pub struct NagaModuleDescriptor<'a> {
    pub source: &'a str,
    pub file_path: &'a str,
    pub shader_type: ShaderType,
    pub shader_defs: HashMap<String, ShaderDefValue>,
    pub additional_imports: &'a [ImportDefinition],
}
```

**Comment by robtfm** [comment]
in bevy we use composable module defs to specify things like `MAX_DIRECTIONAL_LIGHTS`, which is platform specific, and is specified on the `bevy_pbr::pbr_lighting` module. 

generally it's useful if you want to have defs associated with some functionality that are then always available when you import the module that contains that functionality.

if you specify defs in an import and at top level both defs must match or it'll throw an error. 



> As I tested, only the defs past to `make_naga_module` took effect.

this shouldn't happen, do you have a reproduction?

**Comment by floppyhammer** [comment]
So the defs in `ComposableModuleDescriptor` act as a base for the defs in `NagaModuleDescriptor`, right? If I have composable module defs [A = 1, B = 2], Naga module defs [A = 1], then the effective def would be [A = 1, B = 2]. Is this correct?

Yes, I have a demo project for this. https://github.com/floppyhammer/shader_preprocessor_demo

```rs
pub fn load(
    &mut self,
    source: &str,
    module_name: &str,
    all_shader_defs: &[&str],
    defined_shader_defs: &[&str],
)
```

When I set `all_shader_defs` as ["BLUE"] and `defined_shader_defs` as [], the def takes no effect. It's effective when I exchange the two arguments' values.

**Comment by robtfm** [comment]
i only scanned quickly but it looks like you're not importing the composable into your final module?

you need to `#import` it from the top level module for the defs to take effect.

**Comment by floppyhammer** [comment]
I've only got one module though. From my understanding of how to make a shader source, firstly I should call `composer.add_composable_module` on the shader code, then call `composer.make_naga_module` on the same code in order to make a naga module. It seems I'm not using it correctly... I thought, for one shader file, calling `composer.add_composable_module` is a prerequisite for calling `composer.make_naga_module`.

**Comment by robtfm** [comment]
you can just call `make_naga_module` directly if you don't use any imports.

`add_composable_module` registers the composable for importing into other shaders (you must either specify the `as_name` or add a `#define_import_path` directive in the composable, to identify it for the `#import` directive).
