### ISSUE TITLE
ANSI output used with non-ANSI terminals, NO_COLOR

### ISSUE THREAD

**Issue by kornelski** [bevyengine/naga_oil#94]
I'm running my Bevy projects via Sublime Text, which doesn't have a real terminal, only a super basic plaintext log.

The problem is that naga_oil uses ANSI colors on non-WASM targets unconditionally, without checking whether the terminal is compatible. In my case `TERM` is undefined, and I'm running `std::env::set_var("NO_COLOR", "1")` in `main`, but I still get ANSI color output that makes WGSL errors completely unreadable:

<img width="816" alt="Screenshot 2024-06-21 at 00 17 24" src="https://github.com/bevyengine/naga_oil/assets/72159/7f5407ca-f46f-4b5b-95dc-0f5a51e06a96">

**Comment by robtfm** [comment]
i don't understand this well enough to fix it but a pr would be welcome.

**Comment by kornelski** [comment]
@robtfm submitted a fix in #103
