### ISSUE TITLE
Bind group bindings

### ISSUE THREAD

**Issue by kornelski** [bevyengine/naga_oil#95]
When I use compute shaders, I need to create bind group layouts on the Rust side that match the shader. This is a redundant definition and needs to be kept in sync with Rust source.

I'm wondering if this could be automated to have one source of truth for the binding groups and their layout.

For example, could naga parse `@group(0) @binding(0)` WGSL directives and expose them as some Bevy type like `BindGroupLayout`?

or do the inverse, and take `BindGroupLayout`s when parsing a shader, and inject bind group definitions based on the Rust side? 

This would be particularly nice if it supported structs in uniforms, because struct definitions have to be manually kept in sync between Rust and shaders.

**Comment by robtfm** [comment]
> could naga parse `@group(0) @binding(0)` WGSL directives and expose them as some Bevy type like `BindGroupLayout`?

the rust struct can't be fully specified based on what's in the wgsl (eg different sampler types all look the same in wgsl).



> do the inverse, and take `BindGroupLayout`s when parsing a shader, and inject bind group definitions based on the Rust side?

this is more feasible i think, but not something i'm interested in doing myself ... maybe it could be done at the wgpu level in error reporting (`expected @group(0) @binding(0) var base_texture: texture_2d<f32>, found ...`)

**Comment by kornelski** [comment]
It turns out this already exists in WebGPU: [`layout: "auto"`](https://gpuweb.github.io/gpuweb/#enumdef-gpuautolayoutmode) + [getBindGroupLayout](https://gpuweb.github.io/gpuweb/#dom-gpupipelinebase-getbindgrouplayout), but it's not exposed in wgpu.

And for the missing sampler info, [there has been a proposal for a WGSL syntax](https://github.com/gpuweb/gpuweb/issues/4687):

```wgsl
@group(X) @binding(Y) const mySampler = sampler {
  addressModeU: mirror_repeat, // enumerant
  magFilter: linear,
  lodMinClamp: 1, // abstract float
…
};
```
